language: java

before_install:
  - echo "MAVEN_OPTS='-Xmx2048M -Xss128M -XX:+CMSClassUnloadingEnabled -XX:+UseG1GC -XX:-UseGCOverheadLimit'" > ~/.mavenrc

install: skip
script: travis_wait 60 mvn -q install

sudo: required

jdk:
  - openjdk8

cache:
  directories:
  - .autoconf
  - $HOME/.m2
